# Generated by Django 3.0.8 on 2021-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonapetit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='ingredients',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
    ]
