# Generated by Django 3.0.8 on 2021-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonapetit', '0002_menuoption_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
